# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/sdm845-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter starqltechn star2qltechn crownqltechn,$(TARGET_DEVICE)),)

endif
